version: '3'

services:
  # Database
  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: DBDemoGoFiber
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
    networks:
      - wpsite
  
networks:
  wpsite:
    driver: bridge
volumes:
  db_data: