@host=http://localhost:3000/api
#### Create
POST {{host}}/books
Content-Type: application/json

{
    "Title": "sach 05",
    "Description": "sach description 10",
    "Author": "congvo",
    "price": 17
}

#### Get All
GET {{host}}/books

#### Get Book
GET {{host}}/books/2

#### Update book
PUT {{host}}/books/2
Content-Type: application/json

{
    "Title": "sach 02 update"
}

#### Delete Book
DELETE {{host}}/books/2
# -------------------------------------------------------- USER --------------------------------------------------------
### POST Register
POST {{host}}/users/register
Content-Type: application/json

{
    "FullName": "vo the cong",
    "Email": "cong.vo3@softyn.com",
    "Password": "123456"
}

### POST Login
POST {{host}}/users/login
Content-Type: application/json

{
    "email": "cong.vo1@softyn.com",
    "password": "123456"
}