#### Create
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "Title": "sach 05",
    "Description": "sach description 10",
    "Author": "congvo",
    "price": 17
}

#### Get All
GET http://localhost:3000/api/books

#### Get Book
GET http://localhost:3000/api/books/2

#### Update book
PUT http://localhost:3000/api/books/2
Content-Type: application/json

{
    "Title": "sach 02 update"
}

#### Delete Book
DELETE http://localhost:3000/api/books/2