#### Create
POST http://localhost:3000/books
Content-Type: application/json

{
    "Title": "sach 02",
    "Description": "sach description 2",
    "Author": "congvo",
    "price": 17
}

#### Get All
GET http://localhost:3000/books

#### Get Book
GET http://localhost:3000/book/1

#### Update book
PUT http://localhost:3000/book/1
Content-Type: application/json

{
    "Title": "sach 02 update"
}

#### Delete Book
DELETE http://localhost:3000/book/1